apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  selector:
    app: orders
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: weshigbee/consul2-orders
        ports:  
        - containerPort: 3000
        env:
        - name: SHIPMENTS_URL
          value: 'http://shipments:5000'

---
apiVersion: v1
kind: Service
metadata:
  name: mails
spec:
  selector:
    app: mails
  ports:
  - port: 8025
    targetPort: 8025
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mails
  name: mails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mails
  template:
    metadata:
      labels:
        app: mails
    spec:
      containers:
      - name: mails
        image: mailhog/mailhog
        ports:  
        - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: shipments
spec:
  selector:
    app: shipments
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipments
  name: shipments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments
  template:
    metadata:
      labels:
        app: shipments
    spec:
      containers:
      - name: shipments
        image: weshigbee/consul2-shipments
        ports:  
        - containerPort: 5000
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: orders-to-shipments
spec:
  destination:
    name: shipments
  sources:
    - name: orders
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: orders-to-mails
spec:
  destination:
    name: mails
  sources:
    - name: orders
      action: allow
---