apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipments
---
apiVersion: v1
kind: Service
metadata:
  name: shipments
spec:
  selector:
    app: shipments
  ports:
  - port: 9003
    targetPort: 9003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipments
  name: shipments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipments
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: shipments
    spec:
      containers:
      - name: shipments
        image: weshigbee/consul2-shipments
        ports:  
        - containerPort: 9003